[project]
name = "splitwise-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.12.0",
    "httpx>=0.27.0",
    "pydantic>=2.0.0",
    "dotenv>=0.9.9",
]
